### ISSUE TITLE
raise KeyError instead of NoSuchNodeError

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDSynthesis#10]
I like using selections (and everything else) in a pythonic fashion (i.e. if it looks like a dict it should mostly behave like one even if under the hood it's all HDF5). One strength of MDS is hiding all the bookkeeping.

Therefore, it is annoying if a non-existent, say, selection raises *NoSuchNodeError* (no idea what kind of exception this is) when I tried 
```python
try:
   sel = self.sim.selections[name]
except KeyError:
   # do something about it because selection 'name' is not stored in the sim
```
because from the syntax I expected to get a *KeyError*.

**Comment by dotsdl** [comment]
Thanks for filing this issue. Raising exceptions at the level of the frontend (tags, categories, selections) that reflect what is failing at that level is one of the rough edges I hope we can smooth out sooner than later. As you noticed, many of these components raise exception at the level of PyTables, and they are not caught and re-raised in more meaningful ways.
