### ISSUE TITLE
Need test coverage of Sims and Groups.

### ISSUE THREAD

**Issue by dotsdl** [Becksteinlab/MDSynthesis#13]
Pytest is our testing framework of choice, and some basic tests have been written for Container elements (tags and categories), but these need to be expanded to cover all components of Sims and Groups. This includes:
* universes
* selections
* members
* renaming and re-locating
* data (pandas, numpy, and pure-python objects)

Additional, less atomic tests can be added later. These may include, e.g., organizational patterns:
* does everything work when Containers are nested (in another Container's tree)?
* does Foxhound find a Container that has been moved? Does it do it reasonably quickly?

**Comment by cing** [comment]
Thoughts on using the MDAnalysisTests package for testing real PSF/DCDs?

**Comment by dotsdl** [comment]
Good idea, since it saves us having to package our own. I'll add MDAnalysisTests as a dependency for the tests on Travis. Will add this to the docs as well.

**Comment by richardjgowers** [comment]
Hey David, is this still open?

**Comment by dotsdl** [comment]
It is. I've been hammering on #16 and #8 over the past few weeks (see 8d11c581ab6054afd45fced12057ea8452d2cdc4 on the member_aggs branch; required some overhauls, and still working on it), so haven't spent much time on improving this one. 

The ``Container`` API has enough tests for now, but neither ``Sim`` nor ``Group`` have tests for their unique components (universes and selections; members). If you're interested in adding some, I'd suggest working from [here](https://github.com/Becksteinlab/MDSynthesis/blob/master/tests/test_containers.py). This is one of the [issues holding back a first release](https://github.com/Becksteinlab/MDSynthesis/milestones/0.5.0), so any help would certainly speed things along!

**Comment by richardjgowers** [comment]
Ok I'll have a go, I had a read of the current tests, pytest looks very cool to use!

Have you looked at including coverage in your CI? It took me maybe 5 lines and 1 website signup to get it working on MDAnalysis

https://github.com/richardjgowers/mdanalysis/commit/9fb086936417cb17315121dcab1f98cb3fa2ddbb

**Comment by dotsdl** [comment]
> Ok I'll have a go, I had a read of the current tests, pytest looks very cool to use!

Thanks! Yeah, its implementation of fixtures takes a little getting used to, but it makes writing tests for large varieties of inputs, including permutations, a bit less painful. The tests for data storage are a good example.

I'm trying out codecov for test coverage. Just updated the development branch with the appropriate includes in [.travis.yml](https://github.com/Becksteinlab/MDSynthesis/blob/develop/.travis.yml). In addition to coverage, I also added pep8 checks to the test execution line, and this spat out a whole slew of violations. *cracks knuckles*

**Comment by dotsdl** [comment]
The good news is that we so far have 42% test coverage according to pytest. Once we have coverage of Sim- and Group-specific elements, this will probably rise to over 70%.

**Comment by dotsdl** [comment]
Make that 47% test coverage after I removed some old unused code. Beyond code coverage, however, we'll also need [stress tests of file locking mechanisms for both state files and data](https://github.com/Becksteinlab/MDSynthesis/blob/master/tests/test_locks.py). The tricky part with those is that they'll require tests using multiprocessing, and I'm not sure if/how that's done with pytest. It's a separate issue (#22), however.

**Comment by dotsdl** [comment]
We're now up to 62% test coverage. I merged the major changes I made to how ``Group`` works underneath the hood into master, and along with this were some changes to both the ``Sim`` and ``Group`` state file schema. As such, old ``Sim`` and ``Group`` state files won't work anymore; I worked a bit on building a conversion script, but I wasn't sure it was worth the time. In the future, changes to schema will only occur across major releases, and we'll have code built into these Containers to handle updating their schema internally based on stored version numbers.

There's still ``Sim.selections`` to test, along with the features of ``Bundle`` (new!). I'll be working to close the gaps in the coming days.

**Comment by richardjgowers** [comment]
I think the easiest jump in coverage looks like core/aggregators, so I'll make some for them.

**Comment by dotsdl** [comment]
Moving this to 0.5.1; quite a bit of progress has been made, and the gaps will be filled in there.

**Comment by dotsdl** [comment]
This is pretty well done. There may be some cracks yet, but they're not really hiding out in Sims and Groups.
