### ISSUE TITLE
Allow globbing syntax for universe definitions.

### ISSUE THREAD

**Issue by dotsdl** [Becksteinlab/MDSynthesis#15]
When multiple trajectories are needed for a universe definition, it may be useful to allow globbing syntax for the paths stored so that new trajectory files that match the pattern are picked up by the universe. Then again, this feature could be troublesome. How feasible is it to include, and what are some pitfalls?

**Comment by orbeckst** [comment]
I wouldn't add it; MDAnalysis only takes a list, which you can easily generate explicitly with glob.glob(). It might be more confusing, especially if `*` and `?` appear in file names (yes, insane, but...)

**Comment by dotsdl** [comment]
Yeah, I agree this opens up a can of worms, and from my experience the order in which files are returned with glob.glob() can vary, making this unreliable at best. Closing.
