### ISSUE TITLE
online docs are missing class/function reference manual

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDSynthesis#26]
The [online docs](http://mdsynthesis.readthedocs.org) do not contain the doc strings of the individual classes and functions. There should be a module/class/function reference section.

**Comment by dotsdl** [comment]
Thanks for catching this. ``scandir`` is now a depedency, and I forgot to add this to sphinx configuration as a mock module (easiest to do, since we already mock every other dependency) in order for autodoc to succeed to build on readthedocs. Fixed.
