### ISSUE TITLE
Pickled Python data structures cannot be modified in append mode

### ISSUE THREAD

**Issue by cing** [Becksteinlab/MDSynthesis#30]
The problem is pretty straight forward
```
import mdsynthesis as mds
s=mds.Sim("marlar")
s.data['poop']=25
s.data['poop']
25
s.data['poop']=50
s.data['poop']
25
s.data.add('poop', 50)
s.data['poop']
25
s.data['poop2']=[1,2]
s.data['poop2']
[1, 2]
s.data['poop2']=[1,2,3]
s.data['poop2']
[1, 2]
```
I dug a little into this one and the cause of the issue seems to be the file mode ab+, it straight up doesn't work for pickle dumping (see code on mdsynthesis/core/persistence.py:1962 where you use that mode). I can submit a one-line PR that changes the mode to "wb+" if there's no reason not to.

Here's the MDSynthesis-free root of the problem:
```
import pickle
pickle.dump(20, open("marlar.pkl", "ab+"))
pickle.load(open("marlar.pkl","rb"))
20
pickle.dump(30, open("marlar.pkl", "ab+"))
pickle.load(open("marlar.pkl","rb"))
20
pickle.dump(30, open("marlar.pkl", "wb"))
pickle.load(open("marlar.pkl","rb"))
30
```

**Comment by cing** [comment]
Oh, via this [stackoverlow](http://stackoverflow.com/questions/12761991/how-to-use-append-with-pickle-in-python), I discovered that appending to pickles actually does work (for lists and dictionaries) but requires multiple pickle.load() calls to get the data back. The pydata:get_data() method doesn't do multiple pickle.load's so that's still an issue. The way I see it, appending should still be ditched.

**Comment by dotsdl** [comment]
Fixed! There wasn't any reason not to do this, and I wasn't aware of this known problem with using append for pickle dumps. Thanks!
