### ISSUE TITLE
upgrade needed to work with MDAnalysis 0.11.0?

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDSynthesis#43]
The new [MDAnalysis release 0.11.0](https://github.com/MDAnalysis/mdanalysis/wiki/ReleaseNotes0110) breaks parts of the API and it is possible that _MDSynthesis_ needs to be [migrated](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide) and pinned to MDAnalysis >= 0.11.0.

**Comment by dotsdl** [comment]
Yup, good call. The next release will require 0.11.0, but at the moment nothing should break since the only API elements used are atom selections via `AtomGroup.selectAtoms` (which is deprecated, but still fucntional).

**Comment by dotsdl** [comment]
It turns out that with the way MDS applies stored resnums to a Universe's atoms the current behavior of MDAnalysis breaks this mechanism. This is fixed in MDAnalysis/mdanalysis#422.

**Comment by dotsdl** [comment]
Fixed.
